default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lead_manager_development
  username: postgres
  password: Admin1234
  host: localhost

test:
  <<: *default
  database: lead_manager_test
  username: postgres
  password: Admin1234
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>